### ISSUE TITLE
Konkrete not working on Serverminer pixelmon server

### ISSUE THREAD

**Issue by MoonyTheVampire** [Keksuccino/Konkrete#1]
Konkrete keeps sending an error back on me when i try to start my server. Any advice?

**Comment by Keksuccino** [comment]
I don’t think this is possible.
Konkrete is a client-side mod, it will not run on a server and because of that, it can’t throw any errors.

Maybe you mean the warning that Konkrete is a client mod? This is normal ^^

But just in case, please send me your server log containing the error you mentioned.

**Comment by Keksuccino** [comment]
You're playing on 1.12.X, right? This was indeed a bug, but a very weird one! Fixed in Konkrete 1.1.0.1 and FancyMenu 1.6.0.1! Thank you for your report!
