### ISSUE TITLE
crash due to unchecked fabric api internal implementation mixin

### ISSUE THREAD

**Issue by Linguardium** [Keksuccino/Konkrete#20]
https://github.com/Keksuccino/Konkrete/blob/309c477fec7f9d58dafdb9a63e22b16b93cb804a/src/main/java/de/keksuccino/konkrete/mixin/mixins/client/MixinScreenEvents.java#L20

https://mclo.gs/vQNMvfY

Should mark the mixin as not required and null check.

Should also mark tested fabric api versions in fabric.mod.json to prevent issues on versions where implementation may change since you call internal methods that may change even in minor patch releases of fapi

**Comment by Keksuccino** [comment]
- You are using an **old version** of FancyMenu and Konkrete that had problems with this
- That part of the API didn't change in like years, so it is unlikely they will start changing it frequently
-  Without this Mixin, FancyMenu and some of my other mods would basically do nothing at all anymore, so a crash is better than making it optional

**Comment by Keksuccino** [comment]
btw: I'm fully aware this Mixin can cause issues, which is why it isn't present in the 1.20.4 version anymore. I'm also planning to backport this change, but this also requires me to update the mods that have Konkrete as dependency, so it does not have very high priority right now. 

The latest versions of Konkrete and FancyMenu (which triggered the NullPointer most of the time) are using this Mixin in a less aggressive way, so crashes related to that Mixin are very rarely happening in these versions.
