### ISSUE TITLE
Konkrete causes an incompatibility conflict of the Slight Gui Modifications mod on 1.18/1.18.1 (Fabric)

### ISSUE THREAD

**Issue by Disguys** [Keksuccino/Konkrete#8]
Know that you already know about this problem, well, I also wanted to inform you that everything was compatible on 1.17.1, when I updated to 1.18, the Konrkete library became incompatible with Slight Gui Modifications mod. 
Slight Gui Modifications work without Konrkete on 1.18/1.18.1

Logs - https://pastebin.com/MszJSuEz
Crash Report - https://pastebin.com/MnWGVcQ6

Additional information:
System Windows 10
Fabric Loader version 0.12.11

**Comment by Disguys** [comment]
https://github.com/Keksuccino/Konkrete/issues/7

**Comment by NATuan123** [comment]
You have the same problem as me. I said this problem to him too but he hasn't answered yet

**Comment by EGOIST1372** [comment]
I have the same issue

**Comment by EGOIST1372** [comment]
I'm happy to say that with latest [Konkrete](https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric) and latest [Slight GUI modifications](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications) and latest [ARRP](https://www.curseforge.com/minecraft/mc-mods/arrp) and latest [architectury api](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) updates there is no crash at startup of the game and game starts and for me that really loved Satisfying Screenshots feature of SGM it works great without problem. 
But I don't know what happens if you change elements in SGM setting that interfere with konkrete/fancy menu mod and I have no reason to find out. just here to say it's not crashing anymore and Satisfying Screenshots works for me :D

fabric loader v0.13.3 1.18.2
fabric api v0.48.0 1.18.2
slight GUI modification v2.1.0 1.18.2
Konkrete [Fabric] v1.3.3-1 1.18.2
arrp v0.5.7
Architectury v4.1.39 1.18.2

**Comment by Keksuccino** [comment]
Nice, thank you for telling me! :)
