### ISSUE TITLE
Error in Logs

### ISSUE THREAD

**Issue by itsdinkd** [Keksuccino/Konkrete#9]
Latesst fabric loader, mc, and konrete, 

[14:20:45] [Render thread/INFO]: [STDOUT]: ################# ERROR [KONKRETE] #################
[14:20:45] [Render thread/INFO]: [STDOUT]: Failed to invoke event!
[14:20:45] [Render thread/INFO]: [STDOUT]: Event Subscription Class: class de.keksuccino.fancymenu.menu.fancy.helper.CustomizationHelper
[14:20:45] [Render thread/INFO]: [STDOUT]: Event Subscription Method Name: onRenderPost
[14:20:45] [Render thread/INFO]: [STDOUT]: Event Name: de.keksuccino.konkrete.events.client.GuiScreenEvent$DrawScreenEvent$Post
[14:20:45] [Render thread/INFO]: [STDOUT]: ####################################################
[14:20:45] [Render thread/INFO]: [STDOUT]: 
[14:20:45] [Render thread/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[14:20:45] [Render thread/INFO]: [STDERR]: 	at jdk.internal.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.invokeEvent(EventHandler.java:115)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at de.keksuccino.konkrete.events.EventHandler.callEventsFor(EventHandler.java:105)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.redirect$gdg000$onRenderCurrentScreen(class_757.java:10037)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:875)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1117)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:733)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:238)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[14:20:45] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[14:20:45] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException

**Comment by Keksuccino** [comment]
Mod conflict probably

**Comment by itsdinkd** [comment]
Any ideas on what type of mods? and does this error actually do anything/stop anything? I can't tell on my end.

**Comment by Nick1st** [comment]
Please send the following information:

- [x] Modlist
- [x] Full latest.log
- [x] Fabric Version

**Comment by ByPaco10** [comment]
de.keksuccino.**fancymenu.**menu.fancy.helper.CustomizationHelper, its crearly a problem because fancymenu interacting with other mod, i can reproduce this but my modlist is insane and with custom fabric api, if for some reason it helps i am going to post it (sorry for the spam)

 `Mods:`

  [✔️] [1.16.4]+MoreTooltips-1.0.1
  [✔️] [Fabric] Wildfire Female Gender Mod-2.5.3
  [✔️] Adorn-1.14.1+1.16.5
  [✔️] AdvancedReborn-1.16-1.0.0
  [✔️] AE2WTLib-1.2.4-release
  [✔️] agape_space-0.0.17
  [✔️] antighost-1.16.5-fabric0.30.0-1.1.3
  [✔️] appleskin-fabric-mc1.16.x-2.2.0
  [✔️] appliedenergistics2-fabric-8.4.0-alpha.3
  [✔️] architects-palette-fabric-port-1.0
  [✔️] architectury-1.30.53
  [✔️] ArmourToughnessBar-1.0.2
  [✔️] artifacts-4.0.2+fabric
  [✔️] artofalchemy-1.1.0+1.16.5
  [✔️] atlantis-2021.9.21-1.16.5-1.0.5
  [✔️] attribute-fix-fabric-1.0.2
  [✔️] audiooutput-1.16.2-0.0.3
  [✔️] authme-1.16.3-1.4.0
  [✔️] autoreconnect-1.1.0
  [✔️] autoswitch-3.5.2
  [✔️] AxesAreWeapons-1.5.1-fabric-1.16.5
  [✔️] BasicShields-1.2.1-1.16.5
  [✔️] bclib-0.1.45
  [✔️] better-end-0.9.8.5-pre
  [✔️] better-nether-5.0.7
  [✔️] better-withered-mobs-1.5.2
  [✔️] betteranimalsplus-1.16.5-11.0.5-fabric
  [✔️] BetterCaves-Fabric-1.16.5-1.2
  [✔️] betterdroppeditems-1.2.4-1.16.2
  [✔️] BetterDungeons-Fabric-1.16.5-1.0.1
  [✔️] BetterMineshafts-Fabric-1.16.4-1.0.2
  [✔️] BetterStrongholds-Fabric-1.16.5-1.1.1
  [✔️] blockshifter-1.4.0+fabric-1.16.4
  [✔️] blockus-2.1.10+1.16.5
  [✔️] Blur-2.1.0-1.16+fabric
  [✔️] byg-1.3.5
  [✔️] caracal-1.16-1.3.5
  [✔️] Cardinal-Components-API-2.8.3
  [✔️] cc-restiched-1.96.3
  [✔️] charm-fabric-1.16.5-2.3.2
  [✔️] charmonium-fabric-1.16.5-2.3.2
  [✔️] Chunky-1.2.54
  [✔️] clean-logs-1.1.0-all
  [✔️] cleancut-mc1.16-2.1-fabric
  [✔️] cleardespawn-1.16.5-fabric0.30.0-1.1.1
  [✔️] cloth-config-4.14.64-fabric
  [✔️] comforts-fabric-0.0.7-1.16.5
  [✔️] Couplings-1.3.6
  [✔️] CraftPresence-Fabric-1.16.5-Release-1.8.8
  [✔️] Croptopia-1.16.4-5-FABRIC-1.4.0
  [✔️] cullleaves-2.1.0
  [✔️] curios-fabric-0.0.13-1.16.5
  [✔️] curiouselytra-fabric-1.1.1-1.16.5
  [✔️] dark-enchanting-0.2.1+mc.1.16.5
  [✔️] dark-loading-screen-1.6.3
  [✔️] DCCH-2.0+1.16
  [✔️] doublejump-fabric-1.16.1-1.0.0
  [✔️] dynamic-fps-2.0.2
  [✔️] dynview.fabric-1.16.5-1.5
  [✔️] eggtab-1.3.2+1.16-fabric
  [✔️] elementalcreepers-1.3.0
  [✔️] EnchantedToolTips-1.3.5-1.16
  [✔️] enhancedblockentities-0.4--1.16.x
  [✔️] entityculling-fabric-mc1.16.5-1.5.0
  [✔️] Erroring-Entity-Remover-1.0.1+1.16.5
  [✔️] etched-1.1.0-1.16.5-fabric
  [✔️] expandability-2.0.1-forge
  [✔️] expandedstorage-7.3.7+1.16.5
  [✔️] fabric-api-0.42.0Artysen
  [✔️] fabric-experiencebugfix-1.0.0.1
  [✔️] fabric-language-kotlin-1.7.0+kotlin.1.6.0
  [✔️] fabric-language-scala-1.1.0+scala.2.13.6-fat
  [✔️] FabricShieldLib-1.4.5+1.16
  [✔️] fabrictailor_fabric-1.5.0-1.16.5
  [✔️] fancymenu_fabric_2.6.3_MC_1.16.2-1.16.5
  [✔️] farmers-delight-fabric-1.16.5-0.0.7
  [✔️] farsight.fabric-1.16.5-1.5.2
  [✔️] fastfurnace-2.4
  [✔️] fatxporbs-0.0.9+1.16.4
  [✔️] ferritecore-2.1.0-fabric
  [✔️] Flamingo-oh-oh-oh-1.0.4-MC1.16.3-fabric
  [✔️] flytre_lib-0.2.11
  [✔️] forgetmechunk-1.17.X-1.0.3
  [✔️] fpsdisplay-1.4.2+1.16.4
  [✔️] ftb-library-fabric-1605.3.4-build.90
  [✔️] ftb-quests-fabric-1605.3.6-build.76
  [✔️] ftb-teams-fabric-1605.2.3-build.40
  [✔️] geckolib-fabric-1.16.5-3.0.71
  [✔️] give-me-hats-1.16-1.5.1
  [✔️] glassential-fabric-1.16.4-1.1.5
  [✔️] go-fish-1.2.3-beta-1.16.5
  [✔️] grizzlybear-1.16-1.2.0
  [✔️] healthcare-1.0.4
  [✔️] HealthOverlay-1.16.5-4.0.1
  [✔️] Heartbond-1.16-1.0.0
  [✔️] IKnowWhatImDoing-3.0.0-fabric
  [✔️] indium-1.0.0+mc1.16.5
  [✔️] indrev-1.9.18-BETA
  [✔️] InitialInventory-5.0.3.23
  [✔️] InventoryHUD-fabric-[1.16.2-1.16.5]-3.4.1
  [✔️] item-filters-fabric-1605.2.5-build.9
  [✔️] item-model-fix-1.0.3+1.16
  [✔️] jmt_mcmt-1.16.5-0.22.87
  [✔️] justenoughkeys-0.5.3-fabric
  [✔️] konkrete_fabric_1.3.3_MC_1.16.2-1.16.5
  [✔️] krypton-0.1.2
  [✔️] kubejs-fabric-1605.3.19-build.299
  [✔️] lambdynamiclights-fabric-1.3.4+1.16
  [✔️] lazydfu-0.1.2
  [✔️] limitedchunks-1.18.2-2.3
  [✔️] litematica-fabric-1.16.4-0.0.0-dev.20210612.170003
  [📁] literally_chunk_loader (folder)
  [✔️] literally-chunk-loader-1.16-2.0.3
  [✔️] lithium-fabric-mc1.16.5-0.6.6
  [✔️] loadmyresources_fabric_1.0.1_MC_1.16.2-1.16.5
  [✔️] locksmith-fabric-1.0.1+1.16.5
  [✔️] malilib-fabric-1.16.5-0.10.0-dev.21+arne.8
  [✔️] materialisation-3.0.3
  [✔️] mcjtylib-1.16-5.1.4
  [✔️] mechanix-5.0.0
  [✔️] megane-4.1.4
  [✔️] mixintrace-1.0.0
  [✔️] Mo-Glass-1.5-MC1.16.5
  [✔️] mocolors-1.1.2
  [✔️] Modern-Industrialization-0.4.0-alpha.11
  [✔️] modifiers-0.1.1-fabric
  [✔️] modmenu-1.16.22
  [✔️] morevillagers-FABRIC-1.16.5-1.4.1
  [✔️] mostructures-1.2.0-1.16.5
  [✔️] MouseTweaks-fabric-mc1.16.5-2.22
  [✔️] multibeds-[fabric]-1.16-1.0.5
  [✔️] musketmod-1.16.5-fabric-1.2.2
  [✔️] MysticalAgriculture-Refabricated-1.16.5-1.1.7
  [✔️] mythic-mounts-1.16.5-7.0
  [✔️] neutral-animals-1.0.0
  [✔️] ninjaphenix-container-library-1.2.10+1.16.5
  [✔️] notenoughanimations-1.2.4
  [✔️] notenoughcrashes-4.1.4+1.16.5-fabric
  [✔️] observable-0.2.1-fabric
  [✔️] okzoomer-4.0.1+1.16.2
  [✔️] onsoulfire-1.16.5-2
  [✔️] ores_above_diamonds_fabric_1.16.5_1.1
  [✔️] overloadedarmorbar-fabric-1.16.1-5.1
  [✔️] Pehkui-3.3.0+1.14.4-1.19
  [✔️] PigPoop-1.16.4-1.1.3
  [✔️] plasmovoice-fabric-1.16.5-1.2.11
  [✔️] platforms-[fabric]-1.16-1.0.4
  [✔️] pollen-fabric-1.4.1+1.16.5
  [✔️] polymorph-fabric-0.0.14-1.16.5
  [✔️] PresenceFootsteps-r29+1.16.4
  [✔️] quarry-reborn-1.16-0.5.2
  [✔️] quartz-elevator-1.3.0+1.16
  [✔️] quickshulker-1.1.14-1.16
  [✔️] RebornCore-1.16-4.7.3+build.136
  [✔️] reloadAudioDriver-1.0.1
  [✔️] rer-2.1.3
  [✔️] rhino-fabric-1605.1.5-build.75
  [✔️] right-click-harvest-1.1.0+1.16.1-fabric
  [✔️] RoughlyEnoughItems-5.12.385
  [✔️] rpgdifficulty-1.0.4
  [✔️] secretrooms-0.9.5+1.16.5
  [✔️] servertick-mc1.16.5-1.3
  [✔️] shetiphiancore-[fabric]-1.16-1.0.6
  [✔️] SimpleBackpack_Fabric_1.16.5-1.0.38
  [✔️] smoothboot-fabric-1.16.5-1.6.0
  [✔️] sodium-extra-mc1.16.5-0.4.3
  [✔️] sodium-fabric-mc1.16.5-0.2.0+build.4
  [✔️] spark-fabric
  [✔️] spatialharvesters_Fabric_1.16.x-0.11.12
  [✔️] staffofbuilding-1.2.6-1.16.5
  [✔️] starlight-fabric-1.0.0-RC2-1.16.x
  [✔️] statuseffecttimer-1.1.0+1.16.5
  [✔️] styledplayerlist-1.2.0
  [✔️] TacoCraft-1.5.2+mc.1.16.5
  [✔️] TechReborn-1.16-3.8.4+build.236
  [✔️] things-0.1.4
  [✔️] tis3d-1.16.5-forge-1.6.8+30
  [✔️] totemic-overhaul-1.1.5
  [✔️] TRansliterationLib-1.0.4
  [✔️] trapexpansion-1.16.2-1.3.3
  [✔️] traverse-3.3.3
  [✔️] trinkets-2.6.7
  [✔️] true-infinity-1.0.1
  [✔️] veinmining-fabric-0.0.10-1.16.5
  [✔️] whisperwoods-1.16.5-2.1.0-fabric
  [✔️] whyamionfire-1.1.0
  [✔️] wirelessnetworks-1.0.3
  [✔️] wraith-alloy_forgery-1.2.0
  [✔️] wraith-harvestscythes-2.0.4
  [✔️] wthit-2.10.11-fabric
  [✔️] wyml-1.1.2-forge
  [✔️] xlpackets-1.1
  [✔️] xykey-1.1
  [✔️] youre-in-grave-danger-1.0.9
  [✔️] YungsApi-1.16.5-Fabric-9
  
Other info (Idk maybe it is userful): 

`Params:
--version MultiMC5 --gameDir /home/paco/.local/share/multimc/instances/Artysen 3.0/.minecraft --assetsDir /home/paco/.local/share/multimc/assets --assetIndex 1.16`

`Window size: 854 x 480`

`Java Arguments:
[-XX:+UseG1GC, -Dsun.rmi.dgc.server.gcInterval=2147483646, -XX:+UnlockExperimentalVMOptions, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=51, -XX:G1HeapRegionSize=32M, -Xms512m, -Xmx6144m, -Duser.language=en]`

I know i have mods that are for another version of the game **i backported the mods, it isn't that**

And as i previously stated i don't think this is going to help too much, its a insane list of mods

log of the game (ignore almost everything, the juicy part is line 1143 to 1174: [2022-05-15-1.log](https://github.com/Keksuccino/Konkrete/files/8703119/2022-05-15-1.log)

Fabric loader 0.14.5

Fabric API (**CUSTOM**) 0.42+Artysen

**Comment by Keksuccino** [comment]
> Fabric API (CUSTOM) 0.42+Artysen

Well, don't expect things to just work when using unofficial Fabric API forks?
Why don't you use the official one?

`[20:26:28] [Render thread/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)`

You're using MultiMC, which can also cause a lot of problems. That's why I don't officially support it.

`[20:26:28] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "de.keksuccino.konkrete.events.client.GuiScreenEvent$DrawScreenEvent$Post.getGui()" is null`

This can be caused by the custom Fabric API. I'm patching some stuff of the official API, to fix a similar error.
Maybe the fix doesn't work for the unofficial fork.

-----------

There's just too much stuff to point at in your setup. It's impossible to find what's causing it. If you don't want this kind of struggle, just use the official versions of APIs and a better launcher and you will have a lot less problems.

Also consider updating to 1.18.2, since I don't support 1.16 for Fabric anymore (and many other devs too, because it's dead).

**Comment by Snivine** [comment]
Our custom fabric API just literally has one class that was deprecated, and it's up to date with the official fabric API for 1.16.5

for the rest, if MultiMC is causing problems with the mod fair enough, but our fabric API can't be the problem because it's the same API but with one class from a previous version of the API put back in
